### ISSUE TITLE
WithTesting() binds us to the testing framework

### ISSUE THREAD

**Issue by jblackman** [maxcnunes/httpfake#6]
**Problem description**
```go
func WithTesting(t *testing.T) ServerOption
```

WithTesting() takes a `*testing.T` parameter. In a framework such as Godog, individual scenarios should be self-contained, but the need to use a `*testing.T` forces us to use the same object (no thanks to the testing package, which does not let us create our own one). This means that the assertions from one test contaminate another.

Ideally, we should be able to pass in our own testing object. So, could we switch WithTesting() to take an interface instead?

**Suggested solutions**
Switch from struct to interface `testing.TB`, which is already used through the package:

```go
func WithTesting(tb testing.TB) ServerOption
```

On a personal level, I would also suggest also moving from `testing.TB` to an interface that just contains the methods actually used. Most other assertion packages now follow this approach and it makes it much less painful to implement the interface.

I'm happy to do the work and raise a PR if this approach finds favour.

**Comment by maxcnunes** [comment]
hey @jblackman that sounds good to me, although lets hear @erutherford feedback as well since he implemented the assertion support for this package.

**Comment by erutherford** [comment]
Yeah, I think changing to the `testing.TB` interface makes perfect since. I'm honestly not sure why I didn't go that route to begin with.

As far as moving to a more minimal interface, while I agree that a smaller interface makes sense, we also allow people to create their own custom assertors. Most of the methods on that interface probably aren't necessary, but it'd be a breaking change at this point.

**Comment by erutherford** [comment]
It was a pretty quick PR, so I went ahead and made the change while I was in the code.

**Comment by jblackman** [comment]
Saved me the trouble!

**Comment by erutherford** [comment]
This should be resolved with https://github.com/maxcnunes/httpfake/releases/tag/v1.2.3, thank you for your feedback. We can definitely try to work in a smaller interface as a part of future breaking changes.
